export const GET__HOME__PAGE__DATA = "GET__HOME__PAGE__DATA"
export const GET__ALL__CATEGORY__DATA = "GET__ALL__CATEGORY__DATA"

export const GET__PRODUCT__DETAIL__DATA = "GET__PRODUCT__DETAIL__DATA"

export const SET__SELECTED__CATEGORY = "SET__SELECTED__CATEGORY"
export const GET__PRODUCT__FILTER__DATA = "GET__PRODUCT__FILTER__DATA"

export const GET__WISHLIST__DATA = "GET__WISHLIST__DATA"

export const GET__CITY__LOCATION__DATA = "GET__CITY__LOCATION__DATA"
export const GET__COUNTRIES__LOCATION__DATA = "GET__COUNTRIES__LOCATION__DATA"

export const LOADING = "LOADING"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

export const USERLOGGEDIN = "USERLOGGEDIN"
export const GET_HANDSHAKE = "GET_HANDSHAKE"

// common 
export const LOADER_START = "LOADER_START";
export const LOADER_END = "LOADER_END";
export const NOTIFY_SUCCESS_MSG = "NOTIFY_SUCCESS_MSG";
export const NOTIFY_ERROR_MSG = "NOTIFY_ERROR_MSG";
export const NOTIFY_CLEAR_MSG = "NOTIFY_CLEAR_MSG";

// customer 
export const CUSTOMER_DETAILS = "CUSTOMER_DETAILS"
export const CUSTOMER_SIGN_UP_MSG = "CUSTOMER_SIGN_UP_MSG"

// customer addresses
export const CUSTOMER_ADDRESS_LIST = "CUSTOMER_ADDRESS_LIST"

// cart 
export const GET__CART__QUOTE__ID = "GET__CART__QUOTE__ID"
export const GET__CART__DATA = "GET__CART__DATA"
