export const GET__HOME__PAGE__DATA = "GET__HOME__PAGE__DATA"

export const GET__ALL__CATEGORY__DATA = "GET__ALL__CATEGORY__DATA"

export const GET__PRODUCT__DETAIL__DATA = "GET__PRODUCT__DETAIL__DATA"
export const GET__APPLY__FILTER__PRODUCTS__DATA = "GET__APPLY__FILTER__PRODUCTS__DATA"

export const SET__SELECTED__CATEGORY = "SET__SELECTED__CATEGORY"
export const GET__FILTER__DATA = "GET__FILTER__DATA"


export const SET__WISHLIST__COUNT = "SET__WISHLIST__COUNT"
export const GET__WISHLIST__DATA = "GET__WISHLIST__DATA"

export const SET__ORDER__ID__DATA = "SET__ORDER__ID__DATA"
export const GET__ORDER__DETAIL__DATA = "GET__ORDER__DETAIL__DATA"

export const GET__CITY__LOCATION__DATA = "GET__CITY__LOCATION__DATA"
export const GET__COUNTRIES__LOCATION__DATA = "GET__COUNTRIES__LOCATION__DATA"
export const GET__STORES__LOCATION__DATA = "GET__STORES__LOCATION__DATA"

export const LOADING = "LOADING"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

export const USERLOGGEDIN = "USERLOGGEDIN"
export const GET_HANDSHAKE = "GET_HANDSHAKE"

// common 
export const LOADER_START = "LOADER_START";
export const LOADER_END = "LOADER_END";
export const NOTIFY_SUCCESS_MSG = "NOTIFY_SUCCESS_MSG";
export const NOTIFY_ERROR_MSG = "NOTIFY_ERROR_MSG";
export const NOTIFY_CLEAR_MSG = "NOTIFY_CLEAR_MSG";

// customer 
export const CUSTOMER_DETAILS = "CUSTOMER_DETAILS"
export const CUSTOMER_SIGN_UP_MSG = "CUSTOMER_SIGN_UP_MSG"
export const CUSTOMER_LOG_OUT = "CUSTOMER_LOG_OUT"
export const CUSTOMER_SIGN_IN_MSG = "CUSTOMER_SIGN_IN_MSG"
export const CUSTOMER_UPDATE_PASSWORD = "CUSTOMER_UPDATE_PASSWORD"
export const CUSTOMER_PROFILE_DETAILS = "CUSTOMER_PROFILE_DETAILS"
export const CUSTOMER_UPDATE_PROFILE = "CUSTOMER_UPDATE_PROFILE"

// customer addresses
export const CUSTOMER_ADDRESS_LIST = "CUSTOMER_ADDRESS_LIST"

// cart 
export const GET__CART__QUOTE__ID = "GET__CART__QUOTE__ID"
export const GET__CART__DATA = "GET__CART__DATA"
export const CUSTOMER_ADDRESS_ADD_UPDATE = "CUSTOMER_ADDRESS_ADD_UPDATE"
export const CUSTOMER_ADDRESS_ADD_UPDATE_ERR_MSG = "CUSTOMER_ADDRESS_ADD_UPDATE_ERR_MSG"
export const CUSTOMER_ADDRESS_DELETE = "CUSTOMER_ADDRESS_DELETE"
export const UPDATE_CUSTOMER_SHIPPING_INFO = "UPDATE_CUSTOMER_SHIPPING_INFO"

// customer-orders 
export const CUSTOMER_ORDER_LIST = "CUSTOMER_ORDER_LIST"
export const CUSTOMER_ORDER_DETAILS = "CUSTOMER_ORDER_DETAILS"

// other 
export const GET_FLYER_PDF = "GET_FLYER_PDF"